# Generated by Django 3.1 on 2022-03-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='image',
        ),
    ]
